# Generated by Django 4.1.4 on 2022-12-26 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school_code', models.CharField(max_length=150, null=True)),
                ('active_term', models.CharField(default='0', max_length=30)),
                ('full_sch', models.CharField(default='0', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='class_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.CharField(default='', max_length=15, null=True)),
                ('classes', models.CharField(default='', max_length=15, null=True)),
                ('fee', models.FloatField(default=0, max_length=15, null=True)),
                ('datey', models.CharField(choices=[('Creche', 'Creche'), ('Nursery1', 'Nursery1'), ('Nursery2', 'Nursery2'), ('K.G1', 'K.G1'), ('K.G2', 'K.G2'), ('Class1', 'Class1'), ('Class2', 'Class2'), ('Class3', 'Class3'), ('Class4', 'Class4'), ('Class5', 'Class5'), ('Class6', 'Class6'), ('J.H.S1', 'J.H.S1'), ('J.H.S2', 'J.H.S2'), ('J.H.S3', 'J.H.S3')], default='', max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sch_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school_code', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2022, 12, 26))),
                ('full_sch', models.CharField(default='0', max_length=30)),
                ('contact_details', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2022, 12, 26))),
                ('full_sch', models.CharField(default='0', max_length=30)),
                ('contact_details', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
