# Generated by Django 4.1.4 on 2022-12-08 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2022, 12, 8))),
            ],
        ),
    ]
