# Generated by Django 4.1.4 on 2022-12-26 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sch_reg',
            old_name='school_code',
            new_name='school',
        ),
        migrations.AlterField(
            model_name='class_fee',
            name='classes',
            field=models.CharField(choices=[('Creche', 'Creche'), ('Nursery1', 'Nursery1'), ('Nursery2', 'Nursery2'), ('K.G1', 'K.G1'), ('K.G2', 'K.G2'), ('Class1', 'Class1'), ('Class2', 'Class2'), ('Class3', 'Class3'), ('Class4', 'Class4'), ('Class5', 'Class5'), ('Class6', 'Class6'), ('J.H.S1', 'J.H.S1'), ('J.H.S2', 'J.H.S2'), ('J.H.S3', 'J.H.S3')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='class_fee',
            name='datey',
            field=models.CharField(default=datetime.date(2022, 12, 26), max_length=15, null=True),
        ),
    ]
