# Generated by Django 4.1.4 on 2022-12-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_class_fee_datey_alter_sch_reg_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_fee',
            old_name='school_code',
            new_name='school',
        ),
    ]
