# Generated by Django 4.1.4 on 2022-12-20 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_use_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='sch_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('school_code', models.CharField(max_length=150, null=True)),
                ('date', models.DateField(default=datetime.date(2022, 12, 20))),
                ('full_sch', models.CharField(default='0', max_length=10)),
                ('contact_details', models.CharField(default='0', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='use',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 20)),
        ),
    ]
