# Generated by Django 4.1.4 on 2022-12-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_sch_reg_full_sch'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='contact_details',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='use',
            name='full_sch',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='sch_reg',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
        migrations.AlterField(
            model_name='use',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 21)),
        ),
    ]
