# Generated by Django 4.1.4 on 2022-12-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='number',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='school',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
    ]
