# Generated by Django 4.1.4 on 2022-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_level_alter_report_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='report30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(default=0, max_length=30, null=True)),
                ('number', models.CharField(default=0, max_length=30, null=True)),
                ('subjectA', models.CharField(default=0, max_length=30, null=True)),
                ('subjectB', models.CharField(default=0, max_length=30, null=True)),
                ('subjectC', models.CharField(default=0, max_length=30, null=True)),
                ('subjectD', models.CharField(default=0, max_length=30, null=True)),
                ('subjectE', models.CharField(default=0, max_length=30, null=True)),
                ('subjectF', models.CharField(default=0, max_length=30, null=True)),
                ('subjectG', models.CharField(default=0, max_length=30, null=True)),
                ('subjectH', models.CharField(default=0, max_length=30, null=True)),
                ('subjectI', models.CharField(default=0, max_length=30, null=True)),
                ('subjectJ', models.CharField(default=0, max_length=30, null=True)),
                ('subjectK', models.CharField(default=0, max_length=30, null=True)),
                ('subjectL', models.CharField(default=0, max_length=30, null=True)),
                ('school', models.CharField(default=0, max_length=30, null=True)),
                ('level', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(default=0, max_length=30, null=True)),
                ('number', models.CharField(default=0, max_length=30, null=True)),
                ('subjectA', models.CharField(default=0, max_length=30, null=True)),
                ('subjectB', models.CharField(default=0, max_length=30, null=True)),
                ('subjectC', models.CharField(default=0, max_length=30, null=True)),
                ('subjectD', models.CharField(default=0, max_length=30, null=True)),
                ('subjectE', models.CharField(default=0, max_length=30, null=True)),
                ('subjectF', models.CharField(default=0, max_length=30, null=True)),
                ('subjectG', models.CharField(default=0, max_length=30, null=True)),
                ('subjectH', models.CharField(default=0, max_length=30, null=True)),
                ('subjectI', models.CharField(default=0, max_length=30, null=True)),
                ('subjectJ', models.CharField(default=0, max_length=30, null=True)),
                ('subjectK', models.CharField(default=0, max_length=30, null=True)),
                ('subjectL', models.CharField(default=0, max_length=30, null=True)),
                ('school', models.CharField(default=0, max_length=30, null=True)),
                ('level', models.CharField(default=0, max_length=30, null=True)),
            ],
        ),
    ]
