# Generated by Django 4.1.4 on 2022-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_update',
            name='school',
            field=models.CharField(default='', max_length=12, null=True),
        ),
    ]
