# Generated by Django 4.1.4 on 2022-12-29 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0003_alter_fees_update_datey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_update',
            name='datey',
            field=models.DateField(default=datetime.date(2022, 12, 29), max_length=40, null=True),
        ),
    ]
