# Generated by Django 4.1.4 on 2022-12-20 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0004_alter_fees_update_datey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_update',
            name='datey',
            field=models.DateField(default=datetime.date(2022, 12, 20), max_length=40, null=True),
        ),
    ]
