# Generated by Django 4.1.4 on 2022-12-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0005_alter_fees_update_datey'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees_update',
            name='school_full',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
