# Generated by Django 4.1.4 on 2022-12-21 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploading', '0006_fees_update_school_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees_update',
            name='datey',
            field=models.DateField(default=datetime.date(2022, 12, 21), max_length=40, null=True),
        ),
    ]
